name: Build & Publish Packages

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM binary
        run: cd wasm/rust && wasm-pack build --target bundler

      - name: Install dependencies
        run: npm install --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build JS client
        run: npm run build:main --workspace=js

      - name: Build WASM package
        run: npm run build:web --workspace=wasm

      - name: Publish @satvisorcom/buttplug
        run: npm publish --workspace=js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish @satvisorcom/buttplug-wasm
        run: npm publish --workspace=wasm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
